name: 💡 Feature Request
description: Suggest a feature to improve this project
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please describe in detail the functionality you'd like to see.

  - type: textarea
    id: feature-description
    attributes:
      label: 💡 Feature Description
      description: Clearly and concisely describe the feature you'd like to see
      placeholder: Please describe in detail the functionality you'd like to add...
    validations:
      required: true

  - type: textarea
    id: problem-background
    attributes:
      label: 🎯 Problem Background
      description: What problem does this feature solve? Why is this feature needed?
      placeholder: Please describe the specific problem this feature would solve...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 🔧 Proposed Solution
      description: Clearly and concisely describe how you'd like to implement this feature
      placeholder: Please describe your proposed implementation approach...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives
      description: Clearly and concisely describe any alternative solutions or features you've considered
      placeholder: Please describe other approaches you've considered...

  - type: dropdown
    id: priority
    attributes:
      label: ⭐ Priority
      description: The priority of this feature
      options:
        - Low - Nice-to-have feature
        - Medium - Useful improvement
        - High - Important feature
        - Urgent - Essential feature
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: 🧩 Complexity Assessment
      description: How complex do you think implementing this feature would be
      options:
        - Simple - Can be implemented in a few lines of code
        - Medium - Requires some development work
        - Complex - Requires significant development work
        - Very Complex - Requires architectural-level changes
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: 📋 Use Cases
      description: Describe the use cases and users who would benefit from this feature
      placeholder: Please describe who would use this feature and in what situations...

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Information
      description: Add any other context or screenshots about the feature request
      placeholder: Any other relevant information, including screenshots, links, etc...

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm you have completed the following items
      options:
        - label: I have searched existing Issues and confirmed this is a new feature
          required: true
        - label: I have provided a detailed feature description
          required: true
        - label: I have considered implementation approaches
          required: true
        - label: I am willing to help implement this feature
          required: false
