name: Documentation Build

on:
  push:
    branches: [ main, develop ]
    paths: ['docs/**', 'src/**', '*.md']
  pull_request:
    branches: [ main ]
    paths: ['docs/**', 'src/**', '*.md']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
    
    - name: Build documentation
      run: |
        cd docs
        # Use the build script which handles both Sphinx and fallback
        bash build_docs.sh
    
    - name: Check build output
      run: |
        if [ -d "docs/_build/html" ]; then
          echo "Documentation built successfully"
          echo "Files in build directory:"
          ls -la docs/_build/html/
        else
          echo "Documentation build failed"
          exit 1
        fi
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs/_build/html
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v3
